/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * ACM Season Service API
 * API documentation for ACM Season Service
 * OpenAPI spec version: 1.0.0
 */
export interface UpdateTaskRequest {
  /**
     * @minLength 0
     * @maxLength 255
     */
  title: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  description?: string;
  seasonId?: number;
  plannedDate?: string;
  dueDate?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
  assigneeUserId?: number;
}

export interface TaskResponse {
  taskId?: number;
  title?: string;
  description?: string;
  status?: string;
  plannedDate?: string;
  dueDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  notes?: string;
  seasonId?: number;
  seasonName?: string;
  userId?: number;
  userName?: string;
  plotId?: number;
  workTeamId?: number;
  estimatedDays?: number;
  estimatedCompletionDate?: string;
  plotName?: string;
  plotArea?: number;
  baseWage?: number;
  createdAt?: string;
}

export interface ApiResponseTaskResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: TaskResponse;
  data?: TaskResponse;
  generatedAt?: string;
}

export interface UpdateSeasonRequest {
  seasonName: string;
  startDate: string;
  varietyId?: number;
  plannedHarvestDate?: string;
  endDate: string;
  /** @minimum 1 */
  currentPlantCount: number;
  expectedYieldKg?: number;
  actualYieldKg?: number;
  notes?: string;
  description?: string;
}

export interface SeasonDetailResponse {
  id?: number;
  seasonName?: string;
  plotId?: number;
  cropId?: number;
  varietyId?: number;
  plotName?: string;
  cropName?: string;
  varietyName?: string;
  startDate?: string;
  plannedHarvestDate?: string;
  endDate?: string;
  status?: string;
  initialPlantCount?: number;
  currentPlantCount?: number;
  expectedYieldKg?: number;
  actualYieldKg?: number;
  notes?: string;
}

export interface ApiResponseSeasonDetailResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonDetailResponse;
  data?: SeasonDetailResponse;
  generatedAt?: string;
}

export interface UpdateHarvestDetailRequest {
  harvestDate: string;
  /** @minimum 0 */
  quantity: number;
  /** @minimum 0 */
  unit: number;
  grade?: string;
  note?: string;
  qualityGrade?: string;
  qualityNotes?: string;
  subStandardQuantity?: number;
  subStandardDisposition?: string;
  packagingType?: string;
  packagingCount?: number;
  processingType?: string;
  grossWetWeight?: number;
}

export interface HarvestResponse {
  id?: number;
  seasonId?: number;
  seasonName?: string;
  harvestDate?: string;
  quantity?: number;
  unit?: number;
  grade?: string;
  revenue?: number;
  note?: string;
  status?: string;
  createdAt?: string;
  qualityGrade?: string;
  qualityNotes?: string;
  subStandardQuantity?: number;
  subStandardDisposition?: string;
  packagingType?: string;
  packagingCount?: number;
  processingType?: string;
  cropCategory?: string;
  grossWetWeight?: number;
  netDryWeight?: number;
  warehouseReceiptStatus?: string;
  postHarvestDelayDays?: number;
}

export interface ApiResponseHarvestResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: HarvestResponse;
  data?: HarvestResponse;
  generatedAt?: string;
}

export interface UpdateFieldLogRequest {
  logDate: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  logType: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
}

export interface FieldLogResponse {
  id?: number;
  seasonId?: number;
  seasonName?: string;
  logDate?: string;
  logType?: string;
  notes?: string;
  createdByUserId?: number;
  createdByUsername?: string;
  createdByDisplayName?: string;
  createdByType?: string;
  canEdit?: boolean;
  canDelete?: boolean;
  createdAt?: string;
}

export interface ApiResponseFieldLogResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: FieldLogResponse;
  data?: FieldLogResponse;
  generatedAt?: string;
}

export interface UpdateDiseaseTreatmentRequest {
  treatedAt?: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  method?: string;
  supplyItemId?: number;
  supplyLotId?: number;
  /**
     * @minLength 0
     * @maxLength 150
     */
  materialName?: string;
  /** @minimum 0 */
  quantityUsed?: number;
  /**
     * @minLength 0
     * @maxLength 20
     */
  unit?: string;
  /** @minimum 0 */
  costAmount?: number;
  expenseId?: number;
  effectiveness?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  resultSummary?: string;
  nextReviewAt?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
}

export interface DiseaseTreatmentResponse {
  id?: number;
  diseaseRecordId?: number;
  treatedAt?: string;
  method?: string;
  supplyItemId?: number;
  supplyItemName?: string;
  supplyLotId?: number;
  batchCode?: string;
  materialName?: string;
  quantityUsed?: number;
  unit?: string;
  costAmount?: number;
  expenseId?: number;
  effectiveness?: string;
  resultSummary?: string;
  nextReviewAt?: string;
  notes?: string;
  createdByUserId?: number;
  createdByUsername?: string;
  createdByDisplayName?: string;
  createdByType?: string;
  canEdit?: boolean;
  canDelete?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ApiResponseDiseaseTreatmentResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: DiseaseTreatmentResponse;
  data?: DiseaseTreatmentResponse;
  generatedAt?: string;
}

export interface UpdateDiseaseRecordRequest {
  /**
     * @minLength 0
     * @maxLength 150
     */
  diseaseName?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  symptomSummary?: string;
  severity?: string;
  /**
     * @minLength 0
     * @maxLength 30
     */
  status?: string;
  detectedAt?: string;
  /** @minimum 0 */
  affectedPlantCount?: number;
  /** @minimum 0 */
  affectedAreaValue?: number;
  /**
     * @minLength 0
     * @maxLength 20
     */
  affectedAreaUnit?: string;
  /**
     * @minLength 0
     * @maxLength 1000
     */
  evidenceUrl?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
  incidentId?: number;
}

export interface DiseaseRecordResponse {
  id?: number;
  seasonId?: number;
  seasonName?: string;
  plotId?: number;
  plotName?: string;
  cropId?: number;
  cropName?: string;
  varietyId?: number;
  varietyName?: string;
  reportedByUserId?: number;
  reportedByUsername?: string;
  reportedByDisplayName?: string;
  reportedByType?: string;
  canEdit?: boolean;
  canDelete?: boolean;
  incidentId?: number;
  diseaseName?: string;
  symptomSummary?: string;
  severity?: string;
  status?: string;
  detectedAt?: string;
  affectedPlantCount?: number;
  affectedAreaValue?: number;
  affectedAreaUnit?: string;
  evidenceUrl?: string;
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
  treatmentCount?: number;
  latestTreatmentAt?: string;
}

export interface ApiResponseDiseaseRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: DiseaseRecordResponse;
  data?: DiseaseRecordResponse;
  generatedAt?: string;
}

export interface CreateTaskRequest {
  /**
     * @minLength 0
     * @maxLength 255
     */
  title: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  description?: string;
  seasonId?: number;
  plannedDate?: string;
  dueDate?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
  assigneeUserId?: number;
  plotId?: number;
  workTeamId?: number;
  estimatedDays?: number;
  baseWage?: number;
}

export interface CreateSeasonRequest {
  plotId: number;
  cropId: number;
  varietyId?: number;
  seasonName: string;
  startDate: string;
  plannedHarvestDate?: string;
  endDate: string;
  /** @minimum 1 */
  initialPlantCount: number;
  expectedYieldKg?: number;
  notes?: string;
  description?: string;
}

export interface CreatePesticideRecordRequest {
  pesticideName: string;
  activeIngredient?: string;
  phiDays?: number;
  applicationDate: string;
  applicationMethod?: string;
  dosage?: string;
  targetPest?: string;
  note?: string;
}

export interface PesticideRecordResponse {
  id?: number;
  seasonId?: number;
  plotId?: number;
  fieldLogId?: number;
  pesticideName?: string;
  activeIngredient?: string;
  phiDays?: number;
  harvestAllowedDate?: string;
  applicationDate?: string;
  applicationMethod?: string;
  dosage?: string;
  targetPest?: string;
  note?: string;
  createdBy?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface ApiResponsePesticideRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PesticideRecordResponse;
  data?: PesticideRecordResponse;
  generatedAt?: string;
}

export interface AiDiseaseSuggestionRequest {
  suggestedPesticide: string;
  diseaseName?: string;
}

export interface ApiResponseCreatePesticideRecordRequest {
  status?: number;
  code?: string;
  message?: string;
  result?: CreatePesticideRecordRequest;
  data?: CreatePesticideRecordRequest;
  generatedAt?: string;
}

export interface CreateHarvestDetailRequest {
  harvestDate: string;
  /** @minimum 0 */
  quantity: number;
  /** @minimum 0 */
  unit: number;
  warehouseId: number;
  locationId?: number;
  productId?: number;
  productName: string;
  productVariant?: string;
  lotCode: string;
  inventoryUnit?: string;
  grade?: string;
  note?: string;
  qualityGrade?: string;
  qualityNotes?: string;
  subStandardQuantity?: number;
  subStandardDisposition?: string;
  packagingType?: string;
  packagingCount?: number;
  processingType?: string;
  grossWetWeight?: number;
}

export interface CreateDiseaseRecordRequest {
  /**
     * @minLength 0
     * @maxLength 150
     */
  diseaseName: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  symptomSummary?: string;
  severity: string;
  /**
     * @minLength 0
     * @maxLength 30
     */
  status?: string;
  detectedAt: string;
  /** @minimum 0 */
  affectedPlantCount?: number;
  /** @minimum 0 */
  affectedAreaValue?: number;
  /**
     * @minLength 0
     * @maxLength 20
     */
  affectedAreaUnit?: string;
  /**
     * @minLength 0
     * @maxLength 1000
     */
  evidenceUrl?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
  incidentId?: number;
}

export interface StartSeasonRequest {
  actualStartDate?: string;
}

export interface SeasonResponse {
  id?: number;
  seasonName?: string;
  farmId?: number;
  farmName?: string;
  plotId?: number;
  plotName?: string;
  cropId?: number;
  cropName?: string;
  varietyId?: number;
  varietyName?: string;
  startDate?: string;
  plannedHarvestDate?: string;
  endDate?: string;
  status?: string;
  expectedYieldKg?: number;
  actualYieldKg?: number;
}

export interface ApiResponseSeasonResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonResponse;
  data?: SeasonResponse;
  generatedAt?: string;
}

export interface CompleteSeasonRequest {
  endDate: string;
  actualYieldKg?: number;
  forceComplete?: boolean;
}

export interface CancelSeasonRequest {
  forceCancel?: boolean;
  reason?: string;
}

export interface SeasonSummaryDto {
  id?: number;
  seasonName?: string;
  plotId?: number;
  cropId?: number;
  status?: string;
  startDate?: string;
  plannedHarvestDate?: string;
  endDate?: string;
}

export interface CreateFieldLogRequest {
  seasonId?: number;
  logDate: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  logType: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
}

export interface TrainingProgramRequest {
  title: string;
  category?: string;
  description?: string;
  isMandatory?: boolean;
}

export interface TrainingProgramDto {
  id?: number;
  title?: string;
  category?: string;
  description?: string;
  isMandatory?: boolean;
  createdAt?: string;
}

export interface ApiResponseTrainingProgramDto {
  status?: number;
  code?: string;
  message?: string;
  result?: TrainingProgramDto;
  data?: TrainingProgramDto;
  generatedAt?: string;
}

export interface RejectTaskRequest {
  rejectReason: string;
}

export interface PayrollRecalculateRequest {
  employeeUserId?: number;
  periodStart?: string;
  periodEnd?: string;
}

export interface PayrollRecordResponse {
  id?: number;
  seasonId?: number;
  seasonName?: string;
  employeeUserId?: number;
  employeeName?: string;
  periodStart?: string;
  periodEnd?: string;
  totalAssignedTasks?: number;
  totalCompletedTasks?: number;
  wagePerTask?: number;
  totalAmount?: number;
  generatedAt?: string;
  note?: string;
}

export interface ApiResponseListPayrollRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PayrollRecordResponse[];
  data?: PayrollRecordResponse[];
  generatedAt?: string;
}

export interface AddSeasonEmployeeRequest {
  employeeUserId: number;
  /** @minimum 0 */
  wagePerTask?: number;
}

export interface SeasonEmployeeResponse {
  id?: number;
  seasonId?: number;
  seasonName?: string;
  employeeUserId?: number;
  employeeUsername?: string;
  employeeName?: string;
  employeeEmail?: string;
  wagePerTask?: number;
  active?: boolean;
  isTrained?: boolean;
  trainedAt?: string;
  trainingNotes?: string;
  createdAt?: string;
}

export interface ApiResponseSeasonEmployeeResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonEmployeeResponse;
  data?: SeasonEmployeeResponse;
  generatedAt?: string;
}

export interface BulkAssignSeasonEmployeesRequest {
  employeeUserIds: number[];
  wagePerTask?: number;
}

export interface ApiResponseListSeasonEmployeeResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonEmployeeResponse[];
  data?: SeasonEmployeeResponse[];
  generatedAt?: string;
}

export interface EmployeeTrainingRecordRequest {
  workTeamId?: number;
  trainingProgramId: number;
  trainedAt: string;
  trainerName?: string;
  evidenceUrls?: string[];
  certifiedUntil?: string;
}

export interface EmployeeTrainingRecordDto {
  id?: number;
  userId?: number;
  workTeamId?: number;
  trainingProgram?: TrainingProgramDto;
  trainedAt?: string;
  trainerName?: string;
  evidenceUrls?: string[];
  certifiedUntil?: string;
  status?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ApiResponseEmployeeTrainingRecordDto {
  status?: number;
  code?: string;
  message?: string;
  result?: EmployeeTrainingRecordDto;
  data?: EmployeeTrainingRecordDto;
  generatedAt?: string;
}

export interface EmployeeTaskProgressRequest {
  /**
     * @minimum 0
     * @maximum 100
     */
  progressPercent: number;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  note?: string;
  /**
     * @minLength 0
     * @maxLength 1000
     */
  evidenceUrl?: string;
}

export interface TaskProgressLogResponse {
  id?: number;
  taskId?: number;
  taskTitle?: string;
  seasonId?: number;
  seasonName?: string;
  employeeUserId?: number;
  employeeName?: string;
  progressPercent?: number;
  note?: string;
  evidenceUrl?: string;
  loggedAt?: string;
}

export interface ApiResponseTaskProgressLogResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: TaskProgressLogResponse;
  data?: TaskProgressLogResponse;
  generatedAt?: string;
}

export interface DiseaseSuggestionRequest {
  /**
     * @minLength 0
     * @maxLength 2000
     */
  question?: string;
  includeInventory?: boolean;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  additionalNote?: string;
}

export type DiseaseSuggestionResponseUsedContextSummary = {[key: string]: { [key: string]: unknown }};

export interface DiseaseSuggestionResponse {
  diseaseRecordId?: number;
  suggestionText?: string;
  usedContextSummary?: DiseaseSuggestionResponseUsedContextSummary;
  generatedAt?: string;
  warning?: string;
  matchedFromInventory?: boolean;
  matchedSupplyName?: string;
  recommendedProductName?: string;
  recommendedActiveIngredient?: string;
  summary?: string;
  safetyNotes?: string;
  usageInstructions?: string;
}

export interface ApiResponseDiseaseSuggestionResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: DiseaseSuggestionResponse;
  data?: DiseaseSuggestionResponse;
  generatedAt?: string;
}

export interface CreateDiseaseTreatmentRequest {
  treatedAt: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  method: string;
  supplyItemId?: number;
  supplyLotId?: number;
  /**
     * @minLength 0
     * @maxLength 150
     */
  materialName?: string;
  /** @minimum 0 */
  quantityUsed?: number;
  /**
     * @minLength 0
     * @maxLength 20
     */
  unit?: string;
  /** @minimum 0 */
  costAmount?: number;
  expenseId?: number;
  effectiveness?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  resultSummary?: string;
  nextReviewAt?: string;
  /**
     * @minLength 0
     * @maxLength 4000
     */
  notes?: string;
}

export interface StartTaskRequest {
  actualStartDate?: string;
}

export interface TaskDoneRequest {
  actualEndDate?: string;
}

export interface UpdateTaskStatusRequest {
  status: string;
  actualStartDate?: string;
  actualEndDate?: string;
  notes?: string;
}

export interface UpdateSeasonStatusRequest {
  status: string;
  actualStartDate?: string;
  actualEndDate?: string;
  reason?: string;
}

export interface AssignTaskEmployeeRequest {
  employeeUserId: number;
}

export interface UpdatePayrollRecordRequest {
  /**
     * @minLength 0
     * @maxLength 4000
     */
  note?: string;
}

export interface ApiResponsePayrollRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PayrollRecordResponse;
  data?: PayrollRecordResponse;
  generatedAt?: string;
}

export interface UpdateSeasonEmployeeRequest {
  /** @minimum 0 */
  wagePerTask?: number;
  active?: boolean;
  isTrained?: boolean;
  trainedAt?: string;
  trainingNotes?: string;
}

export interface PageResponseTaskResponse {
  items?: TaskResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseTaskResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseTaskResponse;
  data?: PageResponseTaskResponse;
  generatedAt?: string;
}

export interface SeasonMinimalResponse {
  seasonId?: number;
  seasonName?: string;
  farmId?: number;
  farmName?: string;
  plotId?: number;
  plotName?: string;
  startDate?: string;
  endDate?: string;
  plannedHarvestDate?: string;
}

export interface ApiResponseListSeasonMinimalResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonMinimalResponse[];
  data?: SeasonMinimalResponse[];
  generatedAt?: string;
}

export interface PageResponseSeasonResponse {
  items?: SeasonResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseSeasonResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseSeasonResponse;
  data?: PageResponseSeasonResponse;
  generatedAt?: string;
}

export interface ApiResponseListPesticideRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PesticideRecordResponse[];
  data?: PesticideRecordResponse[];
  generatedAt?: string;
}

export interface PageResponseHarvestResponse {
  items?: HarvestResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseHarvestResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseHarvestResponse;
  data?: PageResponseHarvestResponse;
  generatedAt?: string;
}

export interface HarvestStockContextResponse {
  warehouseId?: number;
  warehouseName?: string;
  productName?: string;
  lotCode?: string;
  matchingLots?: number;
  onHandQuantity?: number;
  unit?: string;
}

export interface ApiResponseHarvestStockContextResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: HarvestStockContextResponse;
  data?: HarvestStockContextResponse;
  generatedAt?: string;
}

export interface PageResponseDiseaseRecordResponse {
  items?: DiseaseRecordResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseDiseaseRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseDiseaseRecordResponse;
  data?: PageResponseDiseaseRecordResponse;
  generatedAt?: string;
}

export interface ApiResponseListSeasonResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonResponse[];
  data?: SeasonResponse[];
  generatedAt?: string;
}

export interface MySeasonResponse {
  seasonId?: number;
  seasonName?: string;
  farmId?: number;
  farmName?: string;
  plotId?: number;
  plotName?: string;
  startDate?: string;
  endDate?: string;
  plannedHarvestDate?: string;
  status?: string;
}

export interface ApiResponseListMySeasonResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: MySeasonResponse[];
  data?: MySeasonResponse[];
  generatedAt?: string;
}

export interface TaskInternalDto {
  id?: number;
  title?: string;
  seasonId?: number;
  userId?: number;
  status?: string;
}

export type TrainingComplianceSnapshotDtoMemberCompliance = {[key: string]: boolean};

export interface TrainingComplianceSnapshotDto {
  seasonId?: number;
  totalMembers?: number;
  compliantMembers?: number;
  requiredProgramIds?: number[];
  requiredCategories?: string[];
  memberCompliance?: TrainingComplianceSnapshotDtoMemberCompliance;
  compliant?: boolean;
}

export interface ProductionDiaryEventDto {
  eventDate?: string;
  eventType?: string;
  title?: string;
  description?: string;
  sourceService?: string;
  sourceId?: number;
}

export interface PesticideRecordInternalDto {
  id?: number;
  seasonId?: number;
  pesticideName?: string;
  activeIngredient?: string;
  phiDays?: number;
  harvestAllowedDate?: string;
  applicationDate?: string;
}

export interface SeasonInternalDto {
  id?: number;
  seasonName?: string;
  plotId?: number;
  cropId?: number;
  varietyId?: number;
  status?: string;
  startDate?: string;
  plannedHarvestDate?: string;
  endDate?: string;
}

export interface PlotDependencyStatusDto {
  hasActiveSeasons?: boolean;
  hasActiveTasks?: boolean;
}

export interface HarvestSummaryResponse {
  totalHarvestedKg?: number;
  lotsCount?: number;
  totalRevenue?: number;
  yieldVsPlanPercent?: number;
  expectedYieldKg?: number;
  actualYieldKg?: number;
  totalStoredKg?: number;
  totalSoldKg?: number;
  totalProcessingKg?: number;
  premiumGradePercentage?: number;
}

export interface ApiResponseHarvestSummaryResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: HarvestSummaryResponse;
  data?: HarvestSummaryResponse;
  generatedAt?: string;
}

export interface PageResponseFieldLogResponse {
  items?: FieldLogResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseFieldLogResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseFieldLogResponse;
  data?: PageResponseFieldLogResponse;
  generatedAt?: string;
}

export interface ApiResponseListTrainingProgramDto {
  status?: number;
  code?: string;
  message?: string;
  result?: TrainingProgramDto[];
  data?: TrainingProgramDto[];
  generatedAt?: string;
}

export type ApiResponseMapLongListEmployeeTrainingRecordDtoResult = {[key: string]: EmployeeTrainingRecordDto[]};

export type ApiResponseMapLongListEmployeeTrainingRecordDtoData = {[key: string]: EmployeeTrainingRecordDto[]};

export interface ApiResponseMapLongListEmployeeTrainingRecordDto {
  status?: number;
  code?: string;
  message?: string;
  result?: ApiResponseMapLongListEmployeeTrainingRecordDtoResult;
  data?: ApiResponseMapLongListEmployeeTrainingRecordDtoData;
  generatedAt?: string;
}

export interface ApiResponseListProductionDiaryEventDto {
  status?: number;
  code?: string;
  message?: string;
  result?: ProductionDiaryEventDto[];
  data?: ProductionDiaryEventDto[];
  generatedAt?: string;
}

export interface ApiResponseListTaskProgressLogResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: TaskProgressLogResponse[];
  data?: TaskProgressLogResponse[];
  generatedAt?: string;
}

export interface PageResponseTaskProgressLogResponse {
  items?: TaskProgressLogResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseTaskProgressLogResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseTaskProgressLogResponse;
  data?: PageResponseTaskProgressLogResponse;
  generatedAt?: string;
}

export interface PageResponsePayrollRecordResponse {
  items?: PayrollRecordResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponsePayrollRecordResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponsePayrollRecordResponse;
  data?: PageResponsePayrollRecordResponse;
  generatedAt?: string;
}

export interface PageResponseSeasonEmployeeResponse {
  items?: SeasonEmployeeResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseSeasonEmployeeResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseSeasonEmployeeResponse;
  data?: PageResponseSeasonEmployeeResponse;
  generatedAt?: string;
}

export interface EmployeeDirectoryResponse {
  userId?: number;
  username?: string;
  fullName?: string;
  email?: string;
  phone?: string;
}

export interface PageResponseEmployeeDirectoryResponse {
  items?: EmployeeDirectoryResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseEmployeeDirectoryResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseEmployeeDirectoryResponse;
  data?: PageResponseEmployeeDirectoryResponse;
  generatedAt?: string;
}

export interface TeamProgressSummaryResponse {
  workTeamId?: number;
  teamName?: string;
  plotId?: number;
  totalTasks?: number;
  completedTasks?: number;
  inProgressTasks?: number;
  completionRate?: number;
}

export interface ExpenseCategoryDto {
  category?: string;
  amountVnd?: number;
}

export interface SeasonReportDto {
  seasonId?: string;
  totalYieldKg?: number;
  expectedYieldKg?: number;
  totalExpenseVnd?: number;
  expenseByCategory?: ExpenseCategoryDto[];
}

export interface ApiResponseSeasonReportDto {
  status?: number;
  code?: string;
  message?: string;
  result?: SeasonReportDto;
  data?: SeasonReportDto;
  generatedAt?: string;
}

export interface PHIAlertDto {
  seasonId?: number;
  seasonName?: string;
  pesticideName?: string;
  appliedDate?: string;
  requiredIntervalDays?: number;
  earliestSafeDate?: string;
  daysRemaining?: number;
}

export interface ApiResponseListPHIAlertDto {
  status?: number;
  code?: string;
  message?: string;
  result?: PHIAlertDto[];
  data?: PHIAlertDto[];
  generatedAt?: string;
}

export interface FarmingLogDto {
  id?: string;
  seasonId?: string;
  date?: string;
  activityType?: string;
  description?: string;
  amount?: number;
  unit?: string;
  performedBy?: string;
  status?: string;
  notes?: string;
  materialName?: string;
  quarantineDays?: number;
  soilCondition?: string;
  vietGapCompliant?: boolean;
  vietGapReason?: string;
}

export interface ApiResponseListFarmingLogDto {
  status?: number;
  code?: string;
  message?: string;
  result?: FarmingLogDto[];
  data?: FarmingLogDto[];
  generatedAt?: string;
}

export interface ApiResponseListTaskResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: TaskResponse[];
  data?: TaskResponse[];
  generatedAt?: string;
}

export interface DiseaseRecordDetailResponse {
  record?: DiseaseRecordResponse;
  treatments?: DiseaseTreatmentResponse[];
  treatmentCount?: number;
  latestTreatmentAt?: string;
  totalTreatmentCost?: number;
}

export interface ApiResponseDiseaseRecordDetailResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: DiseaseRecordDetailResponse;
  data?: DiseaseRecordDetailResponse;
  generatedAt?: string;
}

export interface PageResponseDiseaseTreatmentResponse {
  items?: DiseaseTreatmentResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface ApiResponsePageResponseDiseaseTreatmentResponse {
  status?: number;
  code?: string;
  message?: string;
  result?: PageResponseDiseaseTreatmentResponse;
  data?: PageResponseDiseaseTreatmentResponse;
  generatedAt?: string;
}

export type ApiResponseVoidResult = { [key: string]: unknown };

export type ApiResponseVoidData = { [key: string]: unknown };

export interface ApiResponseVoid {
  status?: number;
  code?: string;
  message?: string;
  result?: ApiResponseVoidResult;
  data?: ApiResponseVoidData;
  generatedAt?: string;
}

export type AssignTaskParams = {
workTeamId: number;
plotId: number;
};

export type AssignTask200 = { [key: string]: unknown };

export type UpdateTeamParams = {
teamName: string;
leaderId?: number;
};

export type UpdateTeam200 = { [key: string]: unknown };

export type DeleteTeam200 = { [key: string]: unknown };

export type ListTasksParams = {
/**
 * Filter by status
 */
status?: ListTasksStatus;
/**
 * Filter by season ID
 */
seasonId?: number;
/**
 * Search by title (min 2 chars)
 */
q?: string;
/**
 * Page number (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Sort by field
 */
sortBy?: string;
/**
 * Sort direction
 */
sortDirection?: string;
};

export type ListTasksStatus = typeof ListTasksStatus[keyof typeof ListTasksStatus];


export const ListTasksStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  REVIEWING: 'REVIEWING',
  DONE: 'DONE',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
} as const;

export type SearchSeasonsParams = {
plotId?: number;
cropId?: number;
status?: string;
/**
 * From date (yyyy-MM-dd)
 */
from?: string;
/**
 * To date (yyyy-MM-dd)
 */
to?: string;
/**
 * Page index (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
};

export type ListTasks1Params = {
status?: string;
/**
 * From date (yyyy-MM-dd)
 */
from?: string;
/**
 * To date (yyyy-MM-dd)
 */
to?: string;
/**
 * Page index (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
};

export type ListHarvestsParams = {
/**
 * From date (yyyy-MM-dd)
 */
from?: string;
/**
 * To date (yyyy-MM-dd)
 */
to?: string;
/**
 * Page index (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
};

export type ListDiseaseRecordsBySeasonParams = {
status?: string;
severity?: string;
q?: string;
fromDetectedAt?: string;
toDetectedAt?: string;
page?: number;
size?: number;
};

export type ListFieldLogsParams = {
/**
 * Season ID (required)
 */
seasonId: number;
/**
 * Filter by log type
 */
type?: string;
/**
 * Search text in notes (min 2 chars)
 */
q?: string;
/**
 * From date (yyyy-MM-dd)
 */
from?: string;
/**
 * To date (yyyy-MM-dd)
 */
to?: string;
/**
 * Page index (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
/**
 * Sort field
 */
sort?: string;
};

export type GetTrainingProgramsParams = {
category?: string;
};

export type GetTeamsBySeason200 = { [key: string]: unknown };

export type CreateTeamParams = {
teamName: string;
leaderId?: number;
};

export type CreateTeam200 = { [key: string]: unknown };

export type ListSeasonEmployeesParams = {
keyword?: string;
page?: number;
size?: number;
};

export type ListTreatmentsParams = {
page?: number;
size?: number;
};

export type GetHarvestStockContextParams = {
warehouseId: number;
productName: string;
lotCode: string;
};

export type GetEligibleAssigneesParams = {
taskId?: number;
workTeamId?: number;
};

export type SearchSeasonsByKeywordParams = {
q?: string;
};

export type GetTrainingStatsInternal200 = {[key: string]: EmployeeTrainingRecordDto[]};

export type CountFieldLogsByTypeInternalParams = {
logType: string;
};

export type ListAllHarvestsParams = {
/**
 * Season ID (optional, if absent returns all farmer's harvests)
 */
seasonId?: number;
/**
 * From date (yyyy-MM-dd)
 */
from?: string;
/**
 * To date (yyyy-MM-dd)
 */
to?: string;
/**
 * Page index (0-based)
 */
page?: number;
/**
 * Page size
 */
size?: number;
};

export type GetSummaryParams = {
/**
 * Season ID (optional, if absent returns summary for all farmer's seasons)
 */
seasonId?: number;
};

export type ListSeasonProgressParams = {
employeeUserId?: number;
taskId?: number;
page?: number;
size?: number;
};

export type ListSeasonPayrollParams = {
employeeUserId?: number;
page?: number;
size?: number;
};

export type ListEmployeeDirectoryParams = {
keyword?: string;
page?: number;
size?: number;
};

export type GetTeamProgressSummaryParams = {
seasonId: number;
};

export type GetSeasonStatsParams = {
seasonId: number;
};

export type GetFarmingLogsParams = {
seasonId: number;
};

export type ListAssignedTasksForCurrentEmployeeParams = {
status?: string;
seasonId?: number;
page?: number;
size?: number;
};

export type GetMyTasks200 = { [key: string]: unknown };

export type ListFieldLogsForSeasonParams = {
type?: string;
q?: string;
from?: string;
to?: string;
page?: number;
size?: number;
};

export type ListDiseaseRecordsForSeasonParams = {
status?: string;
severity?: string;
q?: string;
fromDetectedAt?: string;
toDetectedAt?: string;
page?: number;
size?: number;
};

export type ListMyProgressParams = {
page?: number;
size?: number;
};

export type ListMyPayrollParams = {
seasonId?: number;
page?: number;
size?: number;
};

